<a href="https://colab.research.google.com/github/bishair/PirnaCSVDatabase/blob/main/PirnaModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from google.colab import files

In [4]:
file_uploaded = files.upload()

Saving groundwaterCSV.csv to groundwaterCSV.csv


In [62]:
# Read csv into a dataframe
df = pd.read_csv('groundwaterCSV.csv')
print(df.dtypes)

Date     object
G10     float64
dtype: object


In [63]:
df['Date Time'] = pd.to_datetime(df['Date'])
df['Day'] = df['Date Time'].dt.day
df['Month'] = df['Date Time'].dt.month
df['Year'] = df['Date Time'].dt.year
df['Hour'] = df['Date Time'].dt.hour
df['Minue'] = df['Date Time'].dt.minute

df['waterlevel'] = pd.to_numeric(df['G10'], errors='coerce')

df.drop(['Date'],axis=1, inplace=True)
df.drop(['G10'],axis=1, inplace=True)
df.drop(['Date Time'],axis=1, inplace=True)

print(df.head())
print(df.shape)
print(df.shape[0])

   Day  Month  Year  Hour  Minue  waterlevel
0   30      1  2015    12     18     110.722
1   30      1  2015    13     18     110.720
2   30      1  2015    14     18     110.718
3   30      1  2015    15     18     110.715
4   30      1  2015    16     18     110.714
(17538, 6)
17538


In [67]:
X = []
y = []
for i in range(0, df.shape[0]-48):
  X.append(df.iloc[i:i+48,5])    #Water level values in 5th column
  y.append(df.iloc[i+48,5])
print(len(X))
print(len(y))
print('X before',X[:1])
print('y before', y[:5])
X, y = np.array(X) , np.array(y)
print('X numpy array',X[:1])
print('y numpy array', y[:5])

17490
17490
X before [0     110.722
1     110.720
2     110.718
3     110.715
4     110.714
5     110.712
6     110.710
7     110.709
8     110.707
9     110.705
10    110.704
11    110.702
12    110.701
13    110.700
14    110.698
15    110.696
16    110.694
17    110.694
18    110.692
19    110.690
20    110.689
21    110.687
22    110.685
23    110.682
24    110.682
25    110.679
26    110.679
27    110.679
28    110.677
29    110.678
30    110.677
31    110.676
32    110.675
33    110.676
34    110.674
35    110.673
36    110.672
37    110.670
38    110.668
39    110.666
40    110.665
41    110.663
42    110.661
43    110.659
44    110.658
45    110.655
46    110.651
47    110.650
Name: waterlevel, dtype: float64]
y before [110.649, 110.645, 110.642, 110.639, 110.637]
X numpy array [[110.722 110.72  110.718 110.715 110.714 110.712 110.71  110.709 110.707
  110.705 110.704 110.702 110.701 110.7   110.698 110.696 110.694 110.694
  110.692 110.69  110.689 110.687 110.685 110.682 110.6

In [69]:
y = np.reshape(y, (len(y), 1))   #reshaped into length of y rows and 1 column
print(y[:5])
print(len(X))
print(len(y))


[[110.649]
 [110.645]
 [110.642]
 [110.639]
 [110.637]]
17490
17490


In [70]:
pd.DataFrame(X).to_csv('appended_WaterLevel.csv')
pd.DataFrame(y).to_csv('appended_WaterLevel_1.csv')

In [71]:
# Download the file to your local machine
files.download('appended_WaterLevel.csv')
files.download('appended_WaterLevel_1.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [72]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))

X = scaler.fit_transform(X)
y = scaler.fit_transform(y)
print('Shape of X',X[:1])
print('Shape of y',y[:5])
print(X.shape)
print(y.shape)

[[0.8510427  0.85004965 0.8490566  0.84756703 0.84707051 0.84607746
  0.84508441 0.84458788 0.84359484 0.84260179 0.84210526 0.84111221
  0.84061569 0.84011917 0.83912612 0.83813307 0.83714002 0.83714002
  0.83614697 0.83515392 0.8346574  0.83366435 0.8326713  0.83118173
  0.83118173 0.82969215 0.82969215 0.82969215 0.82869911 0.82919563
  0.82869911 0.82820258 0.82770606 0.82820258 0.82720953 0.82671301
  0.82621648 0.82522344 0.82423039 0.82323734 0.82274081 0.82174777
  0.82075472 0.81976167 0.81926514 0.81777557 0.81578947 0.81529295]]
[[0.81479643]
 [0.81281033]
 [0.81132075]
 [0.80983118]
 [0.80883813]]
(17490, 48)
(17490, 1)


In [76]:
X_train, X_test =  X[-13992:],X[:-13992]   #80% 20% split
y_train, y_test =  y[-13992:],y[:-13992]

In [78]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(13992, 48)
(3498, 48)
(13992, 1)
(3498, 1)


In [81]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X_train.shape)
print('Shape of X-train',X_train[:2])

(13992, 48, 1)
Shape of X-train [[[0.25521351]
  [0.25571003]
  [0.25620655]
  [0.2571996 ]
  [0.25819265]
  [0.25819265]
  [0.2591857 ]
  [0.26067527]
  [0.2611718 ]
  [0.26166832]
  [0.26266137]
  [0.26315789]
  [0.26315789]
  [0.26365442]
  [0.26514399]
  [0.26514399]
  [0.26564052]
  [0.26663357]
  [0.26663357]
  [0.26663357]
  [0.26812314]
  [0.26762661]
  [0.26812314]
  [0.26762661]
  [0.26762661]
  [0.26713009]
  [0.26564052]
  [0.26365442]
  [0.26216485]
  [0.26017875]
  [0.25819265]
  [0.25571003]
  [0.25273088]
  [0.25124131]
  [0.24875869]
  [0.24677259]
  [0.24528302]
  [0.24329692]
  [0.24230387]
  [0.24031778]
  [0.23833168]
  [0.23733863]
  [0.23584906]
  [0.23435948]
  [0.23386296]
  [0.23286991]
  [0.23138034]
  [0.23088381]]

 [[0.25571003]
  [0.25620655]
  [0.2571996 ]
  [0.25819265]
  [0.25819265]
  [0.2591857 ]
  [0.26067527]
  [0.2611718 ]
  [0.26166832]
  [0.26266137]
  [0.26315789]
  [0.26315789]
  [0.26365442]
  [0.26514399]
  [0.26514399]
  [0.26564052]
  [0.2

In [84]:
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
print(X_test.shape)

(3498, 48, 1)


In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM
from keras import optimizers

In [ ]:
model = Sequential()
model.add(LSTM(50, return_sequences=True, input_shape=(X_train.shape[1],1)))
model.add(LSTM(50,return_sequences=False))
model.add(Dense(50, activation='relu'))
model.add(Dense(1))


In [ ]:
optimizers.Adam(learning_rate=0.0001)

In [ ]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(X_train,y_train, validation_split=0.2, epochs=100, batch_size=8)

Epoch 1/100
